name: learn.flutter.com
description: flutter interactive playground
version: 1.0.0

flutter:
  assets:
  
  fonts:

environment:
  sdk: '^2.13.4'

dependencies: 
  dio: ^4.0.6
  http: ^0.13.3

dev_dependencies: 
  very_good_analysis: ^2.4.0
  test: ^1.25.15
